services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grafbase
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=200'
    restart: unless-stopped

